com.santo.portfolio.config.txn.categories:
- id: DEPOSIT
  label: Deposit

- id: CREDIT
  label: Credit  
  
- id: REDEEM
  label: Redeem

- id: NAV
  label: Net Value

com.santo.portfolio.config.asset.instruments:
- id: FD
  label: Fixed Deposit
  type: Fixed
      
- id: FSS
  label: Saving Scheme
  type: Fixed
  
- id: EPF
  label: Provident Fund
  type: Fixed        
        
- id: MFE
  label: Equity Fund
  type: Equity
            
- id: MFD
  label: Debt Fund
  type: Equity
      
- id: NPS
  label: Pension Scheme
  type: Equity
      
- id: SGB
  label: Sov Gold Bond
  type: Bullion
    

  
com.santo.portfolio.config.asset.institutions:
- id: DBS  
  label: Digi Bank
  
- id: SBI  
  label: State Bank
  
- id: HDFC  
  label: HDFC
  
- id: BFS  
  label: Bajaj Finserv
  
- id: TNPF  
  label: Power Finance 
  
- id: KUV  
  label: Kuvera
 
- id: COIN  
  label: Zerodha Coin  
  
- id: IPO  
  label: Post Office
  
- id: UAN
  label: UAN  
  
- id: NPS  
  label: NPS
        

com.santo.portfolio.config.asset.holders:
- Lavanya    
- Pranaya
- Santosh


com.santo.portfolio.config.asset.portfolios:
- Education     
- Exigency   
- Relient 
- Welfare 
  
  
com.santo.portfolio.config.asset.status:
- id: A
  label: Active
 
- id: H
  label: Archive
            
- id: D
  label: Delete
