spring:
  config:      
    import:
      - config/categoy.yaml
      - config/instrument.yaml
      - config/institution.yaml       

com.santo.portfolio.config.asset.holders:
- Lavanya    
- Pranaya
- Santosh


com.santo.portfolio.config.asset.portfolios:
- Education     
- Exigency   
- Relient 
- Welfare 
  
  
com.santo.portfolio.config.asset.status:
- id: A
  label: Active
 
- id: H
  label: Archive
            
- id: D
  label: Delete


com.santo.portfolio.config.asset.sortBy:
- id: name
  label: Name
 
- id: current
  label: Current
            
- id: xirr
  label: XIRR
  
com.santo.portfolio.config.asset.sortDirection:
- Ascending
- Descending     
 
