CREATE TABLE PORTFOLIO (
  ID         INT            NOT NULL  AUTO_INCREMENT,
  NAME       VARCHAR(25)    NOT NULL,
  ASSETS     INT            NOT NULL,
  INVESTED   NUMERIC(8,2)   NOT NULL,
  CURRENT    NUMERIC(8,2)   NOT NULL,
  ROI        NUMERIC(8,2)   NOT NULL,

  PRIMARY KEY (ID),
  UNIQUE (NAME)
);