CREATE TABLE PORTFOLIO (
  ID         INT            NOT NULL  AUTO_INCREMENT,
  NAME       VARCHAR(25)    NOT NULL,
  ASSETS     INT            NOT NULL,
  INVESTED   NUMERIC(8,2)   NOT NULL,
  CURRENT    NUMERIC(8,2)   NOT NULL,
  ROI        NUMERIC(8,2)   NOT NULL,

  PRIMARY KEY (ID),
  UNIQUE (NAME)
);

CREATE TABLE ASSET (
  CODE          VARCHAR(8)     NOT NULL,
  NAME          VARCHAR(25)    NOT NULL,
  CATEGORY      VARCHAR(10)    NOT NULL,
  INSTRUMENT    VARCHAR(10)    NOT NULL,
  HOLDER        VARCHAR(10)    NOT NULL,
  INSTITUTION   VARCHAR(10)    NOT NULL,
  FUND_HOUSE    VARCHAR(10)    NOT NULL,
  GROUP         VARCHAR(99)    NOT NULL,
  START_DATE    DATE           NOT NULL,
  END_DATE      DATE           NOT NULL,
  STATUS        VARCHAR(1)     NOT NULL,
  PRIMARY KEY (CODE)
);