SELECT 
	TXN_SUMMARY.ASSET_ID, 
    SUM(TXN_SUMMARY.DEPOSIT) AS DEPOSIT, 
    SUM(TXN_SUMMARY.CREDIT) AS CREDIT
FROM (
	SELECT 
		ASSET_ID,
		(CASE WHEN CATEGORY = 'DEPOSIT' THEN AMOUNT END) AS DEPOSIT,
		(CASE WHEN CATEGORY = 'CREDIT'  THEN AMOUNT END) AS CREDIT
	FROM TXN
) TXN_SUMMARY
GROUP BY TXN_SUMMARY.ASSET_ID