SELECT 
  T.NAME, T.HOLDER, T.INSTITUTION,	SUM(T.DEPOSIT) AS DEPOSIT, SUM(T.CREDIT) AS CREDIT,
  SUM(DEPOSIT + CREDIT) AS TOTAL, SUM(T.MATURITY) AS MATURITY
FROM ( 
	SELECT A.ID, A.NAME, A.HOLDER, A.INSTITUTION,
		(CASE WHEN T.CATEGORY = 'DEPOSIT'  THEN T.AMOUNT ELSE 0 END) AS DEPOSIT,
		(CASE WHEN T.CATEGORY = 'CREDIT'   THEN T.AMOUNT ELSE 0 END) AS CREDIT,
		(CASE WHEN T.CATEGORY = 'MATURITY' THEN T.AMOUNT ELSE 0 END) AS MATURITY
	FROM ASSET A 
	LEFT JOIN TXN T ON T.ASSET_ID = A.ID
	WHERE A.CATEGORY = 'FIXED' AND A.INSTRUMENT = 'DEPOSIT' AND A.STATUS = 'A'
) T
GROUP BY T.ID